ALTER TABLE users 
ADD COLUMN IF NOT EXISTS class_name TEXT,
ADD COLUMN IF NOT EXISTS gender VARCHAR(10),
ADD COLUMN IF NOT EXISTS mobile VARCHAR(15),
ADD COLUMN IF NOT EXISTS department VARCHAR(50);

ALTER TABLE complaints
ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS is_escalated BOOLEAN DEFAULT FALSE;
